name: online_exam
description: "Online Exam is a Flutter mobile app that helps students take
  online exams easily. It supports different question types, tracks progress,
  and gives quick feedback for both students and teachers."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  retrofit: ^4.4.1
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  get_it: ^8.0.0
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
